### ISSUE TITLE
support for PoolMateLive

### ISSUE THREAD

**Issue by audetto** [ihewitt/poolviewer#13]
Hi,

I've got a PoolMateLive.
It creates a COM port /dev/ttyUSB0, but not much happens after that.
I've logged the Windows COM traffic using portmon, in a session where the watch is plugged in, data uploaded (1 set 2 laps) and unplugged.

http://utente.xoom.it/depo/scambio/Portmon.zip

Can it be of any use to add support for it?

Andrea

**Comment by ihewitt** [comment]
Hi,
Yeah I'm just working on getting poolmate live support going at the 
moment.
Been a bit busy recently though to spend time on it. I'll keep you posted.

Cheers,
Ivor.

On Friday 08 May 2015 11:51:03 Andrea wrote:


Hi, 
I've got a PoolMateLive.It creates a COM port /dev/ttyUSB0, but not much 
happens after that.I've logged the Windows COM traffic using portmon, 
in a session where the watch is plugged in, data uploaded (1 set 2 
laps) and unplugged. 
http://utente.xoom.it/depo/scambio/Portmon.zip[1] 
Can it be of any use to add support for it? 
Andrea 
—Reply to this email directly or view it on GitHub[2].[3]




--------
[1] http://utente.xoom.it/depo/scambio/Portmon.zip
[2] https://github.com/ihewitt/poolviewer/issues/13
[3] 
https://github.com/notifications/beacon/AD3_LEkG1vXfdHiosml8D_8cH
Zzi_srtks5oHP0XgaJpZM4EUFaw.gif

**Comment by audetto** [comment]
Cool,

meanwhile I had some fun trying to replicate the communication and felt SOOOOOOOOOOOOOOOOOO good when I saw the light on and the message LINKED on the watch.

Not looked at the actual payload of the communication yet.

Here is my effort

https://gist.github.com/audetto/fa165d241002c88ba91e

**Comment by ihewitt** [comment]
aye, I've got the protocol decoded. The only stumbling block I have at the moment is I can't work out the algorithm for the two byte checksum at the end therefore am limited to simply sending pre-canned messages. This should be enough for syncing, but will prevent setting/changing watch settings.

**Comment by audetto** [comment]
I've made some small progress

1) the Win app sets the time each time it connects to it
data3 = bytearray([0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x01, 0x07, 0x19, 0x05, 0x0F, 0x00, 0x30, 0x36, 0x15, 0x00])

where 0x19 = 25
0x05 = may
and probably 0x0F = 2015

hour is something like 21:54

maybe this is a workaround the fact that the watch does not keep the time well

2) cannot find out how many sets there are to download (chrono or swim), but it is not too bad as if you try to download a non existing set, it will be full of FF. each set is long 261 bytes (including the 4 CRC)
no idea what they mean yet

**Comment by audetto** [comment]
The number of logs seems to come from a call like (CRC omitted)
00, 00, ff, ff, ff, ff, 00, 06, 80, 00, 00, 00
the answer starts with

00, ff, 03, 00, 00, 00, 00, 00

where each time I add a new item (chrono or swim) a new bit gets set (so in this case we have 8+2=10 events)

strange thing is that before I cleared everything I got some bits set to 0 in the middle

00, 00, 9e, fc, 07, 00, 0

9e = 10011110
fc = 11111100
07 = 00000111

so the last 6 (fc) + 3 (07) are contiguous 1 (when I was adding them). I was not able to force it to add a 0.

**Comment by audetto** [comment]
I got a 4 as log type.
It seems to behave like 2 & 3

http://pastebin.com/nJiUvVs2

(changed the out to csv, you might want to look at the data at the top

**Comment by ballinger** [comment]
nice that there is some progress on the pm live version. i am still having issues tough, loaded the ftdi_sio thing and got the new_id file, but nothing happens when i want to sync. no idea how to help you out with information. let me know if i can provide you with anything.

**Comment by audetto** [comment]
I don't think the connection is implemented properly at the moment.
The protocol has been understood and can be tried in this separated app

https://github.com/ihewitt/poolviewer/blob/master/contrib/qttest.cpp

which show it works, but the GUI is not there yet.

**Comment by ballinger** [comment]
thanks for the reply. i see the qttest.cpp file, just how can i test it? thanks.

**Comment by ihewitt** [comment]
just wait for a couple of days and the syncing will be in.
otherwise the commandline to compile qttest is listed at the top of the file.

**Comment by ballinger** [comment]
oh then i will wait :) thanks!

**Comment by davidcallen** [comment]
Nice work on the poolviewer.  Looking fwd to support for the Poolmate Live.  
If you need feeback on testing just shout.

**Comment by ihewitt** [comment]
Initial support finally added, slightly fragile at the moment.
