### ISSUE TITLE
Provide CSV example file

### ISSUE THREAD

**Issue by jerome-labidurie** [ihewitt/poolviewer#14]
Hi,

A great little enhancement would be to provide an example data file.
So poolviewer can be tested and shows its capabilities with real data
screenshots are great, but a bit limited.

Regards
Jérôme

**Comment by ihewitt** [comment]
Sure, will do. I'll put one in once I've finished the poolmate live file format update which is nearly complete.

**Comment by jerome-labidurie** [comment]
included in commit acafa44aeb77558ade30c5053c16e90e2245cf41
