### ISSUE TITLE
live pod crashing

### ISSUE THREAD

**Issue by ballinger** [ihewitt/poolviewer#23]
thanks to audetto and ihewitt for working on the live pod support! no idea if it is ready for prime time, but right now it is crashing if i start the app as a normal user and press sync. works fine as root but does not import the data.

terminal output: http://pastebin.com/uxBMvDUR

**Comment by ihewitt** [comment]
Hi, yes the usb code needs a lot more error checking built in at the moment it assumes everything works. :)
Sounds like you just need to sort out your usb permissions, add:
`SUBSYSTEMS=="usb" ATTRS{idVendor}=="0451" ATTRS{idProduct}=="5051" MODE:="0666"`
to your udev rules file, and see if it works then.

In the meantime I'll get the error conditions saner than crashing.

**Comment by ihewitt** [comment]
Ignore that, remembered while out cycling it's just a serial device you need to permission.
probably just a case of adding your userid into the dialout group.

when you've modprobe'd the ftdio device, done the echo into ftdio_sio, check dmesg to see which device the driver has created e.g.:
`FTDI USB Serial Device converter now attached to ttyUSB0`

then check the group for that device: ls -l /dev/ttyUSB0
`crw-rw---- 1 root dialout 188, 0 Oct 18 17:55 /dev/ttyUSB0`

then make sure your userid is in that group.

**Comment by ihewitt** [comment]
Helpful error messages should now be displayed instead of crashing.

**Comment by ballinger** [comment]
thanks for the reply this seems to be resolved
