### ISSUE TITLE
live pod crashing on import

### ISSUE THREAD

**Issue by ballinger** [ihewitt/poolviewer#25]
the entries are missing in the import menu after the data is pulled from the watch and crashes on pressing import.

QObject: Cannot create children for a parent that is in a different thread.
(Parent is QSerialPort(0x249a470), parent's thread is QThread(0x20e3890), current thread is PodLive(0x2512710)
QObject::connect: Cannot queue arguments of type 'QSerialPort::SerialPortError'
(Make sure 'QSerialPort::SerialPortError' is registered using qRegisterMetaType().)
Segmentation fault (core dumped)

**Comment by ihewitt** [comment]
Hi, can you run with a debug build to get a backtrace for that.
Did the watch sync connect and progress to 100% before the crash.

**Comment by ballinger** [comment]
hi, yes it progresses to 100%
here is the dump: http://pastebin.com/UJCbFSU0
thanks, philip

**Comment by ihewitt** [comment]
hmmm. can you run from inside gdb and paste the crash backtrace. you may need to use
`(gdb) thread apply all bt`
To get the complete report.
Cheers, ivor.

**Comment by ballinger** [comment]
ey, i'm a bit lost here... the only thing i got, which probably isnt that what you need is Temporary breakpoint 1 at 0x40c480: file src/main.cpp, line 28.
Starting program: /home/phil/compile/poolviewer/bin/poolview 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Temporary breakpoint 1, main (argc=1, argv=0x7fffffffdf28) at src/main.cpp:28
28	{

maybe you could write me a bit more detailed instructions.

**Comment by ihewitt** [comment]
Perhaps your gdb config is set to break on main. Try hitting "c" enter...

**Comment by ballinger** [comment]
hmm. maybe you can work with this? http://pastebin.com/uDTdmay4

**Comment by ihewitt** [comment]
Excellent, thanks. Should be fixed.

**Comment by ballinger** [comment]
hey awesome, everything works fine now, thanks to you all!
