### ISSUE TITLE
Watch syncing unreliable

### ISSUE THREAD

**Issue by ihewitt** [ihewitt/poolviewer#32]
Watch syncing seems unreliable on a fast machine.
Might need some more delay/retry logic in the serial code somewhere.

**Comment by audetto** [comment]
Indeed.
Today it does not want to work.

In the sync dialog I get "connect watch" and a seg fault.

line 357 of podlive.cpp

then eventually it worked

**Comment by ihewitt** [comment]
Haven't experienced this for some time, the new serial code seems to handle this ok.
