### ISSUE TITLE
Graphs: average or not

### ISSUE THREAD

**Issue by audetto** [ihewitt/poolviewer#35]
Hi,

I was looking at the graphs (in particular the ones with the volume) and I seem to realise that
the values are averaged per workout. so all my months are about the same simply because I swim the same length each workout.

I was expecting to see the total.

I tried as well to add the option, but after a while I got a bit confused how it works.

Would it make sense to have an option to choose whether to average per workout or have the totals?

**Comment by ihewitt** [comment]
ah yes. :) wonder when someone would notice that.
yeah I've been meaning to fix that for a while, I'll change the bar graphs to total up.

**Comment by ihewitt** [comment]
This should be sorted now, although they'll be tweaked a bit soon with some new graphs.
